### ISSUE TITLE
Doesn't parse when there are additional link parameters

### ISSUE THREAD

**Issue by tpluscode** [jfromaniello/li#6]
`li.parse` doesn't return complete output when there are additional link parameters. 

It seems that the library parses links until it encounters one with extra params and then ignores any that follow.

``` js
li.parse('</3>; rel="next", </2>; rel="prev", </home>; rel="up"; rev="home", </void>; rel="ignored"')
```

returns

``` json
{
  "next": "/3",
  "prev": "/2",
  "home": "/home"
}
```

What's more, if you reverse the params:

``` js
li.parse('</home>; rev="home"; rel="up"')
```

it will return an empty object.

**Comment by jfromaniello** [comment]
Thank you for reporting this. I have fixed the issue.

If you do parse with the string in your example:

```javascript
var example = '</3>; rel="next", </2>; rel="prev", </home>; rel="up"; rev="home", </void>; rel="ignored"';
var parsed =  li.parse(example);
console.dir(parsed);

// { next: '/3', prev: '/2', up: '/home', ignored: '/void' }
```

If you need all attributes, then use `extended: true`:

```javascript
var parsed = li.parse(example, { extended: true });
console.dir(parsed);

// [ { link: '/3', rel: [ 'next' ] },
//   { link: '/2', rel: [ 'prev' ] },
//   { link: '/home', rel: [ 'up' ], rev: [ 'home' ] },
//   { link: '/void', rel: [ 'ignored' ] } ]
```

I might change the interface in the next release. I think you should get all attributes by default.

Let me know if this work for you.
