### ISSUE TITLE
[Feature] Regroup links with same URI

### ISSUE THREAD

**Issue by ehmicky** [jfromaniello/li#8]
First, thanks for your work. This little project makes my life much easier.

This is a feature suggestion.

For example:

```js
li.parse('<my_uri>; rel="first last"')
```

returns:

```js
{ first: 'my_uri', last: 'my_uri' }
```

but:

```js
li.stringify({ first: 'my_uri', last: 'my_uri' })
```

returns:

```js
'<my_uri>; rel="first", <my_uri>; rel="last"'
```

Regrouping links by URI is a best practice for `Link` headers and would result instead in:

```js
'<my_uri>; rel="first last"'
```

**Comment by jfromaniello** [comment]
Thanks for reporting this!
